### PR TITLE
added missing version file

### PR DESCRIPTION
**Pull request by SupervisedThinking**
fix build

### CODE REVIEW

**Comment by nigels-com** [comment]
Looks good.

**Comment by Perlmint** [comment]
Thanks for making PR.
Contents of PR looks good. But, `glew-cmake-release` branch is updated by CI script. Committing manually to this branch is not recommended.

**Comment by Perlmint** [comment]
I feel sorry that I overlooked this PR before fix the issue 😭.

**Comment by SupervisedThinking** [comment]
no problem, having a hassle free working glew lib is worth the work :+1:

**Pull request closed without merging**
