### PR TITLE
public include directory

### PR DESCRIPTION
**Pull request by wang37921**
replace include_directories by target_include_directories
let dependent auto include the glew include directory

### CODE REVIEW

**Comment by Perlmint** [comment]
It looks nice!
but I have a simple request - fix the code style. I will happily merge it when you fix it. :)

**Comment by wang37921** [comment]
fixed, have a look

**Comment by Perlmint** [comment]
Why did you make this redundant merge commit - 5df460a? It makes your changes weird. remove it, please.

**Comment by Perlmint** [comment]
I suggest that reset hard local master branch to ad431ac, and push force it to your remote repo.

example commands
```
git reset --hard ad431ac
git push -f origin master
```

**Comment by wang37921** [comment]
thank you for your patience, check again^_^

**Pull request merged**
